# Generated by Django 4.1.3 on 2022-11-16 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_merchant_consumerprofile_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='issuerId',
            field=models.CharField(default=0, max_length=3, unique=True, validators=[django.core.validators.MinValueValidator(3)]),
            preserve_default=False,
        ),
    ]
