# Generated by Django 4.1.3 on 2022-11-26 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bank_issuerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='issuerId',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
