# Generated by Django 4.1.3 on 2022-11-27 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0003_token'),
        ('users', '0004_alter_bank_issuerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_authorized', models.BooleanField(default=False)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.consumerprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.token')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.transaction')),
            ],
        ),
    ]
