# Generated by Django 4.1.3 on 2022-12-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_transaction_token_transaction_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='token',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cardId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
