# Generated by Django 4.1.3 on 2022-12-09 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_bank_issuerid'),
        ('checkout', '0003_remove_transaction_token_transaction_cardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.consumerprofile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.merchant'),
        ),
    ]
