# Generated by Django 4.1.3 on 2022-11-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_issuer_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='is_tokenized',
            field=models.BooleanField(default=False),
        ),
    ]
