# Generated by Django 4.1.3 on 2022-12-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_bank_issuerid'),
        ('card', '0004_alter_token_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('fullPan', models.CharField(max_length=255)),
                ('expDate', models.DateField()),
                ('consumerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.consumerprofile')),
            ],
        ),
    ]
