# Generated by Django 4.1.3 on 2022-12-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_bankcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='email',
            field=models.EmailField(default='a@b.com', max_length=254),
        ),
    ]
