# Generated by Django 4.1.3 on 2022-12-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_bankcard_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcard',
            old_name='fullPan',
            new_name='fullPAN',
        ),
    ]
