# Generated by Django 4.1.3 on 2022-12-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_bank_issuerid'),
        ('card', '0007_rename_fullpan_bankcard_fullpan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.consumerprofile'),
        ),
    ]
