# Generated by Django 4.1.3 on 2022-12-08 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_card_issuerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='issuerId',
            field=models.CharField(default='123', max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
